I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 522, in script call
  File "game/screens.rpy", line 714, in script call
  File "game/script.rpy", line 1109, in script call
  File "game/screens.rpy", line 714, in script call
  File "game/script.rpy", line 1109, in script call
  File "game/screens.rpy", line 714, in script call
  File "game/script.rpy", line 1109, in script call
  File "game/screens.rpy", line 714, in script call
  File "game/script.rpy", line 1109, in script call
  File "game/script.rpy", line 1109, in script call
  File "game/script.rpy", line 977, in script call
  File "game/script.rpy", line 556, in script
  File "game/script.rpy", line 556, in python
NameError: name 'black_fade' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\execution.py", line 288, in run
    node.execute()
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\ast.py", line 1106, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\Tekken6\Documents\Neerans Work\Other\renpy-6.15.7-sdk\renpy\python.py", line 1331, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 556, in <module>
    "......"
NameError: name 'black_fade' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.15.7.374
A Ren'Py Game 0.0
